### ISSUE TITLE
unable to specify a binary

### ISSUE THREAD

**Issue by shyanneshan** [oliverlee/bazel_clang_format#1]
### Description of the bug
When trying to build, build fails because of clang-format specification.

#### Env
I tried both with @llvm15//:clang-format and move the clang-format to root path but got the same error: 

`ERROR: /volvo/edb/dev/edb/lib1/BUILD:35:11: in (an implicit dependency) attribute of @bazel_clang_format//:defs.bzl%clang_format_aspect aspect on cc_library rule //lib1:common: alias '@bazel_clang_format//:binary' referring to source file '//:clang-format' is misplaced here (expected no files). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation`

**Comment by oliverlee** [comment]
Are you using [bazel-toolchain](https://github.com/grailbio/bazel-toolchain/) to provide `@llvm15`?

Do you have a small example you can share that reproduces the error?

**Comment by shyanneshan** [comment]
Hi, I am not using bazel-toolchain since I have a local one available.

## To reproduce the error with local clang-format


In WORKSPACE
`
git_repository(
    name = "bazel_clang_format",
    commit = "8a47c0fe17efbd97dd25f217f8acf44a07f2b041",  # update as necessary
    remote = "https://github.com/shyanneshan/bazel_clang_format",
)
`

Copy clang-format binary to root path(I am new to bazel so I tried to test with moving it directly in):
`cp /opt/rh/llvm-toolset-11.0/root/usr/bin/clang-format clang-format
`

in BUILD
`exports_files(["clang-format"])`

run
`bazel build //...   --aspects @bazel_clang_format//:defs.bzl%clang_format_aspect   --@bazel_clang_format//:binary=//:clang-format `

Error
`
ERROR: /front_ride_heights/BUILD:6:11: in (an implicit dependency) attribute of @bazel_clang_format//:defs.bzl%clang_format_aspect aspect on cc_library rule //front_ride_heights:front_ride_heights_provider_interface: alias '@bazel_clang_format//:binary' referring to source file '//:clang-format' is misplaced here (expected no files). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation`


## Other errors
In order to use the local binary I also try to modify in wrapper.sh, using absolute path to replace the `$binary`
`/opt/rh/llvm-toolset-11.0/root/usr/bin/clang-format --fcolor-diagnostics --Werror $dry_run $infile > $outfile`

### Shared libraries error
Leads to error
`/opt/rh/llvm-toolset-11.0/root/usr/bin/clang-format: error while loading shared libraries: libLLVM-11.so: cannot open shared object file: No such file or directory`

#### my tries for this error:
1. check existence of so file
    ```
    [root@ee343ca8ae05 bin]# ldd clang-format
            linux-vdso.so.1 =>  (0x00007ffe254ee000)
            libLLVM-11.so => /opt/rh/llvm-toolset-11.0/root/usr/lib64/libLLVM-11.so (0x00007f8735e64000)
            libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f8735c48000)
            libclang-cpp.so.11 => /opt/rh/llvm-toolset-11.0/root/usr/lib64/libclang-cpp.so.11 (0x00007f8732472000)
            libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f873216a000)
            libm.so.6 => /lib64/libm.so.6 (0x00007f8731e68000)
            libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f8731c52000)
            libc.so.6 => /lib64/libc.so.6 (0x00007f8731884000)
            libffi.so.6 => /lib64/libffi.so.6 (0x00007f873167c000)
            libz.so.1 => /lib64/libz.so.1 (0x00007f8731466000)
            librt.so.1 => /lib64/librt.so.1 (0x00007f873125e000)
            libdl.so.2 => /lib64/libdl.so.2 (0x00007f873105a000)
            libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f8730e30000)
            /lib64/ld-linux-x86-64.so.2 (0x00007f873ad43000)
    [root@ee343ca8ae05 bin]# cd /opt/rh/llvm-toolset-11.0/root/usr/lib64/
    [root@ee343ca8ae05 lib64]# ls
    LLVMgold.so  cmake              libLTO.so         libclang-cpp.so.11  liblldCore.so.11    liblldMachO2.so.11        liblldYAML.so.11            pm-utils
    X11          games              libLTO.so.11      libclang.so.11      liblldDriver.so.11  liblldMinGW.so.11         liblldb.so.11               python2.7
    bfd-plugins  libLLVM-11.0.1.so  libRemarks.so     liblldCOFF.so.11    liblldELF.so.11     liblldReaderWriter.so.11  liblldb.so.11.0.1           sse2
    clang        libLLVM-11.so      libRemarks.so.11  liblldCommon.so.11  liblldMachO.so.11   liblldWasm.so.11          liblldbIntelFeatures.so.11  tls
    ```

2. make sure it's in $PATH and $LD_LIBRARY_PATH
    ```
    [root@ee343ca8ae05 third_party]# echo $PATH
    /opt/rh/devtoolset-11/root/usr/bin:/opt/rh/llvm-toolset-11.0/root/usr/bin:/opt/rh/rh-git227/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/volvo/edb/dev/bin/
    [root@ee343ca8ae05 third_party]# echo $LD_LIBRARY_PATH
    /opt/rh/llvm-toolset-11.0/root/usr/lib64:/opt/rh/httpd24/root/usr/lib64
    ```

3. delete the container and re-run one

### Command not found error
Note that if path is not updated, then error would be command not found. This same error happens when we try to integrate with bazel_clang_tidy, so I tried adding --action-env, but still didn't work.
`external/bazel_clang_format/wrapper.sh: line 12: clang-format: command not found`

I am working with Tomas and he had to manually copy everything from bazel_clang_tidy to make it work. But manually copying didn't work for this repo, so I am writing for help, thank you so much!

**Comment by oliverlee** [comment]
Bazel will search certain system paths unless you provide a hermetic toolchain.

If you want to use a local toolchain in a non-standard location, you can try specifying `PATH` with [action_env](https://bazel.build/reference/command-line-reference#flag--action_env). You could also try to use [new_local_repository](https://bazel.build/reference/be/workspace#new_local_repository) along with [sh_binary](https://bazel.build/reference/be/shell#sh_binary) or ([native_binary](https://github.com/bazelbuild/bazel-skylib/blob/main/docs/native_binary_doc.md#native_binary)) to specify the `clang-format` binary. You may also need to specify the other shared libraries (e.g. `libLLVM-11.so`) as well as the dependencies.

```starlark
# //:WORKSPACE.bazel
...

new_local_repository(
    name = "local_llvm_11",
    path = "/opt/rh/llvm-toolset-11.0",
    build_file_content = """
sh_binary(
    name = "clang-format",
    srcs = ["root/usr/bin/clang-format"],
)
...
# other libraries
""",
)
```

```starlark
# .bazelrc
...
build:clang-format --@bazel_clang_format//:binary=@local_llvm_11//:clang-format
...
```

In your run command, don't forget to specify `--output_groups=report` as well.

**Comment by shyanneshan** [comment]
Specifying --action-env didn't work but new_local_repository with sh_binary worked(it seems there's no need to specify shared library). Thank you so much, it really helped me a lot!
