### ISSUE TITLE
Config options for bazel run

### ISSUE THREAD

**Issue by shyanneshan** [oliverlee/bazel_clang_format#2]
Hi, when we are trying to run update, we have specific binary and config that we'd like to use, so we run
```starlark
bazel run @bazel_clang_format//:update 
--@bazel_clang_format//:binary=@local_clang_format_repo//:clang-format   
--@bazel_clang_format//:config=//:.clang-format -- //lib1:common
```

it works perfectly, in the generated bazel_clang_format.update.sh, we see that the configurations are successfully passed to the script:
```starlark
bazel_format=("$bazel" build \
                    --noshow_progress \
                    --ui_event_filters=-info,-stdout \
                    --color=no \
                    --aspects=@bazel_clang_format//:defs.bzl%clang_format_aspect \
                    --@bazel_clang_format//:binary=@local_clang_format_repo//:clang-format \
                    --@bazel_clang_format//:config=@//:.clang-format \
                    --output_groups=report)
``` 

but we failed when try to simplify the commandline by configuring it in .bazelrc like:

```starlark
run:clang-format --@bazel_clang_format//:binary=@local_clang_format_repo//:clang-format
run:clang-format --@bazel_clang_format//:config=//:.clang-format
```

and run with `bazel run @bazel_clang_format//:update --config clang-format -- //lib1:common`, the run was successful but no actual formatting work was done.

check bazel_clang_format.update.sh, the customized binary path isn't there: 
```starlark
bazel_format=("$bazel" build \
                    --noshow_progress \
                    --ui_event_filters=-info,-stdout \
                    --color=no \
                    --aspects=@bazel_clang_format//:defs.bzl%clang_format_aspect \
                    --@bazel_clang_format//:binary=@bazel_clang_format//:default_binary \
                    --@bazel_clang_format//:config=@bazel_clang_format//:default_config \
                    --output_groups=report)
```

We would like to ask if it's possible to simplify the bazel run command by adding configuration to the .bazelrc.

**Comment by oliverlee** [comment]
You can use the `bazel_clang_format` rule to define a target that uses a specific binary and config.

See the example here:
https://github.com/oliverlee/bazel_clang_format#defaults-without-bazelrc

Does that work for you?

**Comment by shyanneshan** [comment]
Unfortunately that didn't work, so we decided still to use it in command line, thank you so much
